name: Apropriacao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 18,20,23 * * 1,2,3,4,5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: nanasess/setup-chromedriver@v1
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      
        
      with:
        java-version: '1.8'
        server-id: github 
        settings-path: ${{ github.workspace }}
        chromedriver-version: '99.0.4844.51'
    - run: |
       google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
         xvfb-run --server-args="-screen 0 2880x1800x24" ./run_tests.sh
         xvfb-run --server-args="-screen 0 2880x1800x24" ./run_tests.sh
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml test


