name: Apropriacao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 18,20,23 * * 1,2,3,4,5'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      
        
      with:
        java-version: '1.8'
        server-id: github 
        settings-path: ${{ github.workspace }}
        chromedriver-version: '99.0.4844.51'
    - run: chromedriver --chromedriver-version
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml test


